url: "www.hardishukla.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Hardi Shukla" # the name of your site, e.g. ACME Corp.
king: "Me"

minima:
  show_excerpts: true